[
  {
    
    "ProgramName": "BA in Art (Art History)",
    "Level": "Undergraduate",
    "Concentration": "Art History",
    "Description": "The Bachelor of Arts in Art History offers students a comprehensive understanding of the history of art from global perspectives, emphasizing critical thinking and visual literacy.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/arts-letters/art/art-history.html",
    "Accreditation": "WASC, NASAD",
    "QsWorldRanking": "N/A",
    "Department": "Art",
    "College": "College of Arts and Letters",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "High School Diploma or equivalent; Completion of A-G college preparatory courses with grades of C- or better.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": false,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "93%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2025-01-15T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A (Flat Fee)",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      },
      {
        "Term": "Spring 2026",
        "LiveDate": "2025-08-01T00:00:00",
        "DeadlineDate": "2025-11-01T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A (Flat Fee)",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 2,
    "ProgramName": "BS in Computer Science",
    "Level": "Undergraduate",
    "Concentration": "N/A",
    "Description": "The Bachelor of Science in Computer Science prepares students for careers in software engineering, system architecture, and computer applications with a strong foundation in theory and practice.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/engineering-computer-science/computer-science/",
    "Accreditation": "ABET, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Computer Science",
    "College": "College of Engineering and Computer Science",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "High School Diploma; Completion of A-G requirements; Strong Math background recommended (Pre-Calculus/Calculus).",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": true,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "90%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2024-11-30T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A (Flat Fee)",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 3,
    "ProgramName": "MBA (Master of Business Administration)",
    "Level": "Graduate",
    "Concentration": "General Management, Finance, Marketing",
    "Description": "The MBA program is designed to provide aspiring leaders with the skills necessary to succeed in a complex global business environment. AACSB accredited.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/business-administration/graduate/",
    "Accreditation": "AACSB, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Business Administration",
    "College": "College of Business",
    "Requirements": {
      "Resume": "Required",
      "StatementOfPurpose": "Required",
      "GreOrGmat": "GMAT/GRE Waiver Available",
      "EnglishScore": "TOEFL iBT 80 / IELTS 6.5",
      "Requirements": "Bachelor's degree from accredited institution; 2 Letters of Recommendation; Professional Resume.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": false,
      "IsAnalyticalOptional": true,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": true,
      "IsGMATRequired": true,
      "IsGreRequired": true,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": true,
      "IsStemProgram": false,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "60%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2025-03-01T23:59:59",
        "Fees": "$4,771 + $285/unit (Prof. Fee)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "$285 (Business Fee)",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "105",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "500",
      "MinimumGreScore": "300",
      "MinimumIELTSScore": "6.5",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "65",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "80",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 4,
    "ProgramName": "MS in Civil Engineering",
    "Level": "Graduate",
    "Concentration": "Environmental, Geotechnical, Structural, Transportation, Water Resources",
    "Description": "Advanced study in civil engineering disciplines involving research, design, and analysis of infrastructure systems.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/engineering-computer-science/civil-engineering/",
    "Accreditation": "ABET, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Civil Engineering",
    "College": "College of Engineering and Computer Science",
    "Requirements": {
      "Resume": "Required",
      "StatementOfPurpose": "Required",
      "GreOrGmat": "Required for some applicants",
      "EnglishScore": "TOEFL iBT 80 / IELTS 6.5",
      "Requirements": "BS in Civil Engineering or equivalent; Minimum GPA 3.0 in last 60 units.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": false,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": true,
      "IsGMATRequired": false,
      "IsGreRequired": true,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": true,
      "IsStemProgram": true,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "3.0",
      "PreviousYearAcceptanceRates": "75%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2025-03-15T23:59:59",
        "Fees": "$4,771 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "105",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "300",
      "MinimumIELTSScore": "6.5",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "65",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "80",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 5,
    "ProgramName": "BS in Nursing (BSN)",
    "Level": "Undergraduate",
    "Concentration": "Pre-Licensure",
    "Description": "The BSN program prepares students for the NCLEX-RN exam and professional nursing practice. It is an impacted program with high admission standards.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/health-human-services/nursing/",
    "Accreditation": "CCNE, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Nursing",
    "College": "College of Health and Human Services",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "TEAS Exam Required; Minimum GPA 3.3 in prerequisite science/non-science courses; Supplemental Application required.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": false,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "3.3",
      "PreviousYearAcceptanceRates": "15%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2024-11-30T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      },
      {
        "Term": "Spring 2026",
        "LiveDate": "2025-08-01T00:00:00",
        "DeadlineDate": "2025-08-31T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 6,
    "ProgramName": "MA in Education (Curriculum & Instruction)",
    "Level": "Graduate",
    "Concentration": "Curriculum & Instruction",
    "Description": "Designed for educators seeking to enhance their teaching practice and curriculum development skills through research and advanced study.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/education/masters-programs/",
    "Accreditation": "WASC, CTC",
    "QsWorldRanking": "N/A",
    "Department": "Graduate & Professional Studies in Education",
    "College": "College of Education",
    "Requirements": {
      "Resume": "Required",
      "StatementOfPurpose": "Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 80 / IELTS 6.5",
      "Requirements": "Bachelor's degree; Teaching Credential (optional but recommended); 2 Letters of Rec; 2.5-3.0 GPA.",
      "WritingSample": "Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": true,
      "IsStemProgram": false,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "80%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2025-03-01T23:59:59",
        "Fees": "$4,771 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "105",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.5",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "65",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "80",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 7,
    "ProgramName": "BS in Biological Sciences (Biomedical Sciences)",
    "Level": "Undergraduate",
    "Concentration": "Biomedical Sciences",
    "Description": "This concentration is designed for students interested in medical, dental, or other health professional careers, focusing on human biology and disease.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/natural-sciences-mathematics/biology/",
    "Accreditation": "WASC",
    "QsWorldRanking": "N/A",
    "Department": "Biological Sciences",
    "College": "College of Natural Sciences and Mathematics",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "High School Diploma; A-G completion; Chemistry and Biology coursework recommended.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": true,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "88%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2024-12-15T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 8,
    "ProgramName": "Doctor of Physical Therapy (DPT)",
    "Level": "Graduate/Doctorate",
    "Concentration": "Physical Therapy",
    "Description": "A three-year professional doctoral program preparing students for licensure as physical therapists.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/health-human-services/physical-therapy/",
    "Accreditation": "CAPTE, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Physical Therapy",
    "College": "College of Health and Human Services",
    "Requirements": {
      "Resume": "Required",
      "StatementOfPurpose": "Required",
      "GreOrGmat": "GRE Required",
      "EnglishScore": "TOEFL iBT 80 / IELTS 6.5",
      "Requirements": "Bachelor's Degree; Prerequisite coursework (Anatomy, Physiology, Physics, Chem, Psych); 100 Clinical Observation Hours; 3 Letters of Rec.",
      "WritingSample": "Required (Essay)",
      "IsAnalyticalNotRequired": false,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": true,
      "IsGMATRequired": false,
      "IsGreRequired": true,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": true,
      "IsStemProgram": true,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "3.0",
      "PreviousYearAcceptanceRates": "10%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-07-01T00:00:00",
        "DeadlineDate": "2024-11-01T23:59:59",
        "Fees": "$10,081 per semester (Doctoral rate)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "N/A",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "290",
      "MinimumIELTSScore": "7.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "65",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "89",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 9,
    "ProgramName": "BA in Psychology",
    "Level": "Undergraduate",
    "Concentration": "General Psychology",
    "Description": "The psychology major provides a broad background in the basic principles of behavior and experience, research methods, and data analysis.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/social-sciences-interdisciplinary-studies/psychology/",
    "Accreditation": "WASC",
    "QsWorldRanking": "N/A",
    "Department": "Psychology",
    "College": "College of Social Sciences and Interdisciplinary Studies",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "High School Diploma; A-G requirements met.",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": false,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "92%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2024-12-15T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  },
  {
    "ProgramID": 10,
    "ProgramName": "BS in Mechanical Engineering",
    "Level": "Undergraduate",
    "Concentration": "N/A",
    "Description": "Mechanical engineering focuses on the design and operation of mechanical systems, thermal systems, and manufacturing processes.",
    "ProgramWebsiteURL": "https://www.csus.edu/college/engineering-computer-science/mechanical-engineering/",
    "Accreditation": "ABET, WASC",
    "QsWorldRanking": "N/A",
    "Department": "Mechanical Engineering",
    "College": "College of Engineering and Computer Science",
    "Requirements": {
      "Resume": "Not Required",
      "StatementOfPurpose": "Not Required",
      "GreOrGmat": "Not Required",
      "EnglishScore": "TOEFL iBT 64 / IELTS 6.0",
      "Requirements": "High School Diploma; A-G requirements; Strong Math/Physics grades (C or better).",
      "WritingSample": "Not Required",
      "IsAnalyticalNotRequired": true,
      "IsAnalyticalOptional": false,
      "IsDuoLingoRequired": false,
      "IsELSRequired": false,
      "IsGMATOrGreRequired": false,
      "IsGMATRequired": false,
      "IsGreRequired": false,
      "IsIELTSRequired": true,
      "IsLSATRequired": false,
      "IsMATRequired": false,
      "IsMCATRequired": false,
      "IsPTERequired": false,
      "IsTOEFLIBRequired": true,
      "IsTOEFLPBTRequired": true,
      "IsEnglishNotRequired": false,
      "IsEnglishOptional": false,
      "IsRecommendationSystemOpted": false,
      "IsStemProgram": true,
      "IsACTRequired": false,
      "IsSATRequired": false,
      "MaxFails": null,
      "MaxGPA": "4.0",
      "MinGPA": "2.5",
      "PreviousYearAcceptanceRates": "85%"
    },
    "TermDetails": [
      {
        "Term": "Fall 2025",
        "LiveDate": "2024-10-01T00:00:00",
        "DeadlineDate": "2024-11-30T23:59:59",
        "Fees": "$4,009 per semester (residents)",
        "AverageScholarshipAmount": "Varies",
        "CostPerCredit": "N/A",
        "ScholarshipAmount": "Varies",
        "ScholarshipPercentage": "N/A",
        "ScholarshipType": "Merit and Need-based"
      }
    ],
    "TestScores": {
      "MinimumACTScore": "N/A",
      "MinimumDuoLingoScore": "100",
      "MinimumELSScore": "N/A",
      "MinimumGMATScore": "N/A",
      "MinimumGreScore": "N/A",
      "MinimumIELTSScore": "6.0",
      "MinimumMATScore": "N/A",
      "MinimumMCATScore": "N/A",
      "MinimumPTEScore": "50",
      "MinimumSATScore": "N/A",
      "MinimumTOEFLScore": "64",
      "MinimumLSATScore": "N/A"
    }
  }
]